WIP - new branch containing new UI changes
dvsa/mot-automated-testsuite pull request #111
Opened 2019-03-18 12:50 UTC by karlbeckettbjss

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/java/uk/gov/dvsa/mot/fixtures/mot/TesterDoesStepDefinitions.java
> +                //And I click the "Change" link for the colour by clicking the link containing change-under-test/colour
Does not need the extra bit at the end

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/java/uk/gov/dvsa/mot/fixtures/mot/TesterDoesStepDefinitions.java
> +                //And I click the "Change" link for the engine by clicking the link containing change-under-test/engine
Does not need the extra bit at the end

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
> +    And I check the registration plate {registration1} is shown within the registration number span text
Ordering need to change, should do the checks from top to bottom

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
> +    And I check the registration plate {registration1} is shown within the registration number span text
See above

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
> +    And I check the vehicle summary section of the test summary has "Result" of "FAIL"
See above comment

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
> +    And I check the vehicle summary section of the test summary has "Result" of "FAIL"
See above comment

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
> +    And I check the registration plate {registration1} is shown within the registration number span text
See above comment

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05c - tester does.feature
> +
Remove extra line

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/07 - tester records contingency.feature
> +    And I check the vehicle summary section of the test summary has "Result" of "PASS"
Wording could be improving

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/07 - tester records contingency.feature
> +    And I check the vehicle summary section of the test summary has "Result" of "PASS"
Wording could be improved

2019-03-19 10:46 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/12a - vehicle examiner.feature
> +  Scenario: VE re-inspection Fail to Statutory Appeal Verified Pass
Well done :D

2019-03-25 15:45 UTC, karlbeckettbjss commented
Green run's complete

2019-03-25 15:45 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/07 - tester records contingency.feature
> +    And I check the vehicle summary section of the test summary has "Result" of "PASS"
I didn't get time to change this

2019-03-25 15:46 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/07 - tester records contingency.feature
> +    And I check the vehicle summary section of the test summary has "Result" of "PASS"
I didn't get time to change this

2019-03-25 17:05 UTC, ibrahimjassat requested changes

2019-03-25 17:05 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
> +
Remove this line

2019-03-25 17:05 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05a - tester does.feature
>      And The page title contains "MOT test complete"
Would have the new line here as this goes onto a new page

2019-03-25 17:05 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/05b - tester does.feature
> +
Remove empty line

2019-03-25 20:02 UTC, ibrahimjassat approved these changes

2019-03-25 20:03 UTC, merged