Axe accessibilty
dvsa/mot-automated-testsuite pull request #128
Opened 2019-05-14 14:19 UTC by demihennelly

2019-05-15 09:27 UTC, karlbeckettbjss requested changes
We might need to rebase because of the recent changes..

Karl or Ibrahim will make these changes

2019-05-15 09:27 UTC, karlbeckettbjss commented on src/main/java/uk/gov/dvsa/mot/fixtures/generic/WebStepDefinitions.java
> +        Then("^I create an accessibility report \"([^\"]*)\"$", (String filename) ->
We need to add this step to mot-automated-testsuite/docs/step-definitions.md

2019-05-15 09:27 UTC, karlbeckettbjss commented on src/main/resources/features/accessibility/01 - tester.feature
> +    And I create an accessibility report "tester_homepage"
Could we use the page name for the report name?

2019-05-15 09:27 UTC, karlbeckettbjss commented on src/main/resources/features/accessibility/02 - moth.feature
> +Feature: MOT History accessibility reports
should we add recalls and certificate downlands into this journey?
It depends if these new accessibility report steps are going to be added into the current tests/

2019-05-15 13:31 UTC, ibrahimjassat commented
> We might need to rebase because of the recent changes..
> 
> Karl or Ibrahim will make these changes

rebased and pushed back up

2019-05-16 16:04 UTC, karlbeckettbjss approved these changes

2019-05-17 09:40 UTC, ibrahimjassat approved these changes

2019-05-17 10:13 UTC, merged