Fixes to security questions
dvsa/mot-automated-testsuite pull request #143
Opened 2019-08-12 14:50 UTC by JGBJSS

2019-08-12 14:56 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/20 - forgotten card.feature
>      Given I login and click "Lost, forgotten or damaged security" card using "2FA_CARD_USER" as {username}, {lastDrift}, {question1}, {question2}
Do we still need the SQL returning the {question1} and {question2} data?

2019-08-12 14:57 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/21 - lost card.feature
>      Given I login and click "Lost, forgotten or damaged security" card using "2FA_CARD_USER" as {username}, {lastDrift}, {question1}, {question2}
Do we still need the SQL returning the {question1} and {question2} data?

2019-08-12 14:57 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/21 - lost card.feature
>      Given I login and click "Lost, forgotten or damaged security" card using "2FA_CARD_USER" as {username}, {lastDrift}, {question1}, {question2}
Do we still need the SQL returning the {question1} and {question2} data?

2019-08-12 14:58 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Second memorable answer - enter a memorable answer"
Remove the duplication

2019-08-12 14:59 UTC, karlbeckettbjss requested changes

2019-08-12 14:59 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Choose a question from the list"
Remove the duplication

2019-08-12 14:59 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Choose a question from the list"
Remove the duplication

2019-08-12 14:59 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Enter a memorable answer"
Remove the duplication

2019-08-12 14:59 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Enter a memorable answer"
Remove the duplication

2019-08-12 14:59 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Choose a question from the list"
Remove the duplication

2019-08-12 14:59 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/24 - change Q&A according to new policy.feature
> +    Then The page contains "Enter a memorable answer"
Remove the duplication

2019-08-14 14:20 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/20 - forgotten card.feature
>      Given I login and click "Lost, forgotten or damaged security" card using "2FA_CARD_USER" as {username}, {lastDrift}, {question1}, {question2}
No longer Required

2019-08-14 14:20 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/21 - lost card.feature
>      Given I login and click "Lost, forgotten or damaged security" card using "2FA_CARD_USER" as {username}, {lastDrift}, {question1}, {question2}
No longer Required

2019-08-14 14:21 UTC, karlbeckettbjss commented on src/main/resources/features/theme 1/21 - lost card.feature
>      Given I login and click "Lost, forgotten or damaged security" card using "2FA_CARD_USER" as {username}, {lastDrift}, {question1}, {question2}
No longer Required

2019-08-15 11:00 UTC, ibrahimjassat approved these changes

2019-08-15 11:00 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/20 - forgotten card.feature
> +    And The page title contains "MOT testing service"
Should this "changes your security question" - bug in the application

2019-08-15 11:00 UTC, ibrahimjassat commented on src/main/resources/features/theme 1/21 - lost card.feature
> +    And The page title contains "MOT testing service"
Same above

2019-08-15 11:00 UTC, karlbeckettbjss approved these changes

2019-08-15 11:00 UTC, merged