WIP: Feature bl 9633 moth regression automation
dvsa/mot-automated-testsuite pull request #145
Opened 2019-09-24 15:55 UTC by karlbeckettbjss

2019-09-25 10:24 UTC, ibrahimjassat commented on src/main/resources/features/moth/06 - dvla vehicle eu classification.feature
> +Feature: 06 - DVLA vehicle with and with EU classifications
Feature name doesn't make sense

2019-10-08 08:43 UTC, ibrahimjassat commented on src/main/resources/features/moth/08 - invalid registration.feature
> +    @karl1
Don't forget to remove this

2019-10-08 08:53 UTC, karlbeckettbjss commented on src/main/resources/features/moth/08 - invalid registration.feature
> +    @karl1
Removed

2019-10-28 14:06 UTC, ibrahimjassat requested changes

2019-10-28 14:06 UTC, ibrahimjassat commented on docs/step-definitions.md
> +* I enter ```{key}``` in the hidden registration field
Would like to have a second opinion of having this test/step in the AAT as it affects security of the project

2019-10-28 14:06 UTC, ibrahimjassat commented on drivers/readme.txt
> +mac-chromedriver - ChromeDriver 74.0.3729.6 for MacOSX (64-bit)
Should it not be the latest stable version

2019-10-28 14:06 UTC, ibrahimjassat commented on src/main/java/uk/gov/dvsa/mot/framework/WebDriverWrapper.java
> +     * @param labelText2 The 2md element text to find
typo 2nd

2019-10-28 15:52 UTC, karlbeckettbjss commented on drivers/readme.txt
> +mac-chromedriver - ChromeDriver 74.0.3729.6 for MacOSX (64-bit)
Nope, we are no longer keeping the chromedrivers in the repo, it will need to be installed seperatly via the instructions in the readme file

2019-10-28 15:52 UTC, karlbeckettbjss commented on docs/step-definitions.md
> +* I enter ```{key}``` in the hidden registration field
It's worth nothing that all the MOTH tests already show how to get around the security of the page, but please do get a second opinion.

2019-10-30 08:22 UTC, karlbeckettbjss commented on src/main/java/uk/gov/dvsa/mot/framework/WebDriverWrapper.java
> +     * @param labelText2 The 2md element text to find
Fixed

2019-11-05 15:39 UTC, ibrahimjassat requested changes

2019-11-05 15:39 UTC, ibrahimjassat commented on src/main/resources/features/moth/18b - Print MOT certificates - PP.feature
> +  @karl1
Remove before merging

2019-11-05 15:39 UTC, ibrahimjassat commented on src/main/resources/features/moth/18b - Print MOT certificates - PP.feature
> +  @karl
Remove before merging

2019-11-05 15:39 UTC, ibrahimjassat commented on src/main/resources/features/moth/18b - Print MOT certificates - PP.feature
> +  @karl
Same again

2019-11-05 15:39 UTC, ibrahimjassat commented on src/main/resources/features/moth/18b - Print MOT certificates - PP.feature
> +  @karl
Same again

2019-11-05 15:39 UTC, ibrahimjassat commented on src/main/resources/features/moth/18b - Print MOT certificates - PP.feature
> +  @karl
Same again

2019-11-05 15:39 UTC, ibrahimjassat commented on src/main/resources/features/moth/18b - Print MOT certificates - PP.feature
> +  @karl
Same again

2019-11-14 11:36 UTC, karlbeckettbjss commented on docs/step-definitions.md
> +* I enter ```{key}``` in the hidden registration field
Any update to this as I would like to get these changes merged in

2019-11-14 14:28 UTC, merged